# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Forge < Formula
  desc "The StormForger Command Line Client, called 'forge'"
  homepage "https://stormforger.com"
  version "0.52.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stormforger/cli/releases/download/v0.52.1/forge_v0.52.1_darwin_amd64.zip"
      sha256 "498e9455c3e4a4bd1dd614c8aaf6d1d54cd2e50215f1afcf4e9695c1f7ab74dc"

      def install
        bin.install "forge"

        # generate and install bash completion
        output = Utils.safe_popen_read("#{bin}/forge", "completion", "bash")
        (bash_completion/"forge").write output

        # generate and install zsh completion
        output = Utils.safe_popen_read("#{bin}/forge", "completion", "zsh")
        (zsh_completion/"_forge").write output
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/stormforger/cli/releases/download/v0.52.1/forge_v0.52.1_darwin_arm64.zip"
      sha256 "71720f4c6334fafcd83f6a6f6e1803a06cecdc05e7efa1a5a8be1d23a0ce7c39"

      def install
        bin.install "forge"

        # generate and install bash completion
        output = Utils.safe_popen_read("#{bin}/forge", "completion", "bash")
        (bash_completion/"forge").write output

        # generate and install zsh completion
        output = Utils.safe_popen_read("#{bin}/forge", "completion", "zsh")
        (zsh_completion/"_forge").write output
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/stormforger/cli/releases/download/v0.52.1/forge_v0.52.1_linux_amd64.tar.gz"
      sha256 "27def698c70529542e7491594ae23b78e20853985be33ee96ea83b53cd4e3dc9"

      def install
        bin.install "forge"

        # generate and install bash completion
        output = Utils.safe_popen_read("#{bin}/forge", "completion", "bash")
        (bash_completion/"forge").write output

        # generate and install zsh completion
        output = Utils.safe_popen_read("#{bin}/forge", "completion", "zsh")
        (zsh_completion/"_forge").write output
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stormforger/cli/releases/download/v0.52.1/forge_v0.52.1_linux_arm64.tar.gz"
      sha256 "8b77fe2265778ba364adef014d9725ed5d352a5041cced942459b1b8d8bac935"

      def install
        bin.install "forge"

        # generate and install bash completion
        output = Utils.safe_popen_read("#{bin}/forge", "completion", "bash")
        (bash_completion/"forge").write output

        # generate and install zsh completion
        output = Utils.safe_popen_read("#{bin}/forge", "completion", "zsh")
        (zsh_completion/"_forge").write output
      end
    end
  end
end
