# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Forge < Formula
  desc "The StormForger Command Line Client, called 'forge'"
  homepage "https://stormforger.com"
  version "0.50.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/stormforger/cli/releases/download/v0.50.2/forge_v0.50.2_darwin_arm64.zip"
      sha256 "df705dc03018d4e0e3067686bf4cadc3959edc506cd7142eb3a0e78e38c22a1e"

      def install
        bin.install "forge"

        # generate and install bash completion
        output = Utils.safe_popen_read("#{bin}/forge", "completion", "bash")
        (bash_completion/"forge").write output

        # generate and install zsh completion
        output = Utils.safe_popen_read("#{bin}/forge", "completion", "zsh")
        (zsh_completion/"_forge").write output
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/stormforger/cli/releases/download/v0.50.2/forge_v0.50.2_darwin_amd64.zip"
      sha256 "0362d7306cb6a2bac33ef70a6cf44671660b20b0c9f6aa684854f1fe6295c008"

      def install
        bin.install "forge"

        # generate and install bash completion
        output = Utils.safe_popen_read("#{bin}/forge", "completion", "bash")
        (bash_completion/"forge").write output

        # generate and install zsh completion
        output = Utils.safe_popen_read("#{bin}/forge", "completion", "zsh")
        (zsh_completion/"_forge").write output
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stormforger/cli/releases/download/v0.50.2/forge_v0.50.2_linux_arm64.tar.gz"
      sha256 "a1b049be357bfddda47e6d8e811a3e4b7830590b50d58073f2f48e2c8a6b283f"

      def install
        bin.install "forge"

        # generate and install bash completion
        output = Utils.safe_popen_read("#{bin}/forge", "completion", "bash")
        (bash_completion/"forge").write output

        # generate and install zsh completion
        output = Utils.safe_popen_read("#{bin}/forge", "completion", "zsh")
        (zsh_completion/"_forge").write output
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/stormforger/cli/releases/download/v0.50.2/forge_v0.50.2_linux_amd64.tar.gz"
      sha256 "6d017e133c9acaeb7dc5bd372389b1bd39a3f086d0d4e69ec112300ca1cde335"

      def install
        bin.install "forge"

        # generate and install bash completion
        output = Utils.safe_popen_read("#{bin}/forge", "completion", "bash")
        (bash_completion/"forge").write output

        # generate and install zsh completion
        output = Utils.safe_popen_read("#{bin}/forge", "completion", "zsh")
        (zsh_completion/"_forge").write output
      end
    end
  end
end
